[package]
name = "flex"
version = "0.1.0"
authors = ["Daniel Brooks <db48x@db48x.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
